const data = {
    products: [
      {
        _id: '1',
        name: 'Nike Shirts',
        category: 'Shirts',
        image: '/images/i1.jpg',
        price: 490,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product, comfortable fit, uplifts look',
      },
      {
        _id: '2',
        name: 'Polo t-shirts',
        category: 't-shirts',
        image: '/images/i3.jpg',
        price: 799,
        countInStock: 20,
        brand: 'Polo',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product, comfortable fit, uplifts look',
      },
      {
        _id: '3',
        name: 'Allen solly Shirt',
        category: 'Shirts',
        image: '/images/i4.jpg',
        price: 1299,
        countInStock: 0,
        brand: 'Allen solly',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product, comfortable fit, uplifts look',
      },
      {
        _id: '4',
        name: 'Denim Jeans',
        category: 'Pants',
        image: '/images/i5.jpg',
        price: 2399,
        countInStock: 15,
        brand: 'Denim',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product, comfortable fit, uplifts look',
      },
      {
        _id: '5',
        name: 'Jeans for men',
        category: 'Pants',
        image: '/images/i6.jpg',
        price: 1499,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product, comfortable fit, uplifts look',
      },
      {
        _id: '6',
        name: 'Slim-fit Jeans',
        category: 'Pants',
        image: '/images/i7.jpg',
        price: 1499,
        countInStock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product, comfortable fit, uplifts look',
      },
      {
        _id: '7',
        name: 'Why t-shirts',
        category: 'T-shirts',
        image: '/images/i8.jpg',
        price: 499,
        countInStock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product, comfortable fit, uplifts look',
      },
      {
        _id: '8',
        name: 'Unisex Jeans',
        category: 'Pants',
        image: '/images/i10.jpg',
        price: 1499,
        countInStock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product, comfortable fit, uplifts look',
      }
    ],
  };
  export default data;
  